<!DOCTYPE html>
<html>
    <head>
        <title>Vacancy application</title>
        <link rel="stylesheet" href="/media/css/bootstrap.css" />
        <link rel="stylesheet" href="/media/css/index.css" />
        <script type="text/javascript" src="/media/js/jquery-2.1.3.min.js"></script>
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
        <div class="container main">
            <div class="banner"><h1>Job for everyone</h1></div>
            <?php include $template; ?>
        </div>
    </body>
</html>
