<div class="form-inline">
    <div class="form-group">
        <label for="department">Department:</label>
        <select id="department" class="form-control">
            <option value="0">all</option>
            <?php foreach ($departments as $language) : ?>
                <option value="<?php echo $language->getId(); ?>"><?php echo $language->getName(); ?></option>
            <?php endforeach; ?>
        </select>
    </div>
    <div class="form-group">
        <label for="lang">Language:</label>
        <select id="lang" class="form-control">
            <?php foreach ($languages as $language) : ?>
                <option value="<?php echo $language->getId(); ?>"><?php echo $language->getLang(); ?></option>
            <?php endforeach; ?>
        </select>
    </div>
    <div class="form-group">
        <button onclick="Vacancy.filter()" class="btn btn-default">show</button>
    </div>
</div>
<div class="vacancy-list">
    <div class="vacancy-item-source row" style="display:none!important">
        <div class="vacancy-item-id col-md-1"></div>
        <div class="vacancy-item-name col-md-3"></div>
        <div class="vacancy-item-desc col-md-3"></div>
        <div class="vacancy-item-lang col-md-2"></div>
        <div class="vacancy-item-department col-md-3"></div>
    </div>
<?php foreach ($repository as $item) : ?>
    <div class="vacancy-item row">
        <div class="vacancy-item-id col-md-1"><?php echo $item->getId(); ?></div>
        <div class="vacancy-item-name col-md-3"><?php echo $item->getName(); ?></div>
        <div class="vacancy-item-desc col-md-3"><?php echo $item->getDesc(); ?></div>
        <div class="vacancy-item-lang col-md-2"><?php echo $item->getLanguage();?></div>
        <div class="vacancy-item-department col-md-3"><?php echo $item->getDepartment(); ?></div>
    </div>
<?php endforeach; ?>
</div>


<script type="text/javascript">
    var Vacancy = {
        filter: function () {
            var $department = $("#department").val();
            var $lang = $("#lang").val();

            $.post('/filter/', {department: $department, language: $lang}, function (data) {
                var $item = $(".vacancy-item-source");
                $(".vacancy-list .vacancy-item").remove();

                if (data.vacancies) {
                    for (var i = 0; i < data.vacancies.length; i++) {
                        var item = data.vacancies[i];
                        var $fillItem = $item.clone();
                        $fillItem.children(".vacancy-item-id").html(item.id);
                        $fillItem.children(".vacancy-item-name").html(item.name);
                        $fillItem.children(".vacancy-item-desc").html(item.desc);
                        $fillItem.children(".vacancy-item-lang").html(item.language);
                        $fillItem.children(".vacancy-item-department").html(item.department);
                        $fillItem.removeClass("vacancy-item-source");
                        $fillItem.addClass("vacancy-item");
                        $fillItem.show();
                        $(".vacancy-list").append($fillItem);
                    };
                }

            });
        }
    }
</script>